version: '3.6'

services:
  backend:
    image: "gadai:0.1"
    restart: always
    environment:
      - GROUP_ID=2
      - RAILS_ROOT=/home/app
      - DATABASE_ADAPTER=postgresql
      - DATABASE_NAME=block_production
      - DATABASE_HOST=192.168.0.121
      - DATABASE_PORT=5432
      - DATABASE_USER=Alone
      - DATABASE_PASS=Alone123!*
      - RABBITMQ_HOST=192.168.0.121
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - ENCRYPTION_KEY=8eH4y0P/vGq3Gf0GTmqooDPrYL4tbNFDqFyRhQGWA9s=
      - BLOCK_EXCHANGE_NAME=blockchain
      - BLOCK_QUEUE_NAME='blockchain_queue'
      - BLOCK_ROUTEING_KEY=blockchain.fetch_block
      - RPC_BSC_NETWORK=https://data-seed-prebsc-1-s1.bnbchain.org:8545
      - RPC_TRON_NETWORK=https://api.nileex.io
      - SECRET_KEY_BASE=12345678913456
    ports:
      - "3000:3000"
    command: bash -c "bundle exec puma --config config/puma.rb"
    logging:
      driver: "json-file"
      options:
          max-size: "50m"

  schaning_block:
    image: "gadai:0.1"
    restart: always
    environment:
      - GROUP_ID=2
      - RAILS_ROOT=/home/app
      - DATABASE_ADAPTER=postgresql
      - DATABASE_NAME=block_production
      - DATABASE_HOST=192.168.0.121
      - DATABASE_PORT=5432
      - DATABASE_USER=Alone
      - DATABASE_PASS=Alone123!*
      - RABBITMQ_HOST=192.168.0.121
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - ENCRYPTION_KEY=8eH4y0P/vGq3Gf0GTmqooDPrYL4tbNFDqFyRhQGWA9s=
      - BLOCK_EXCHANGE_NAME=blockchain
      - BLOCK_QUEUE_NAME='blockchain_queue'
      - BLOCK_ROUTEING_KEY=blockchain.fetch_block
      - RPC_BSC_NETWORK=https://data-seed-prebsc-1-s1.bnbchain.org:8545
      - RPC_TRON_NETWORK=https://api.nileex.io
      - SECRET_KEY_BASE=12345678913456
    command: bash -c "bundle exec ruby lib/daemons/amqp_daemon.rb schaning_block"
    logging:
      driver: "json-file"
      options:
          max-size: "50m"

  proces_block:
    image: "gadai:0.1"
    restart: always
    volumes:
      - ./app/services:/home/app/app/services
    ports:
      - "3001:3000"
    environment:
      - GROUP_ID=2
      - RAILS_ROOT=/home/app
      - DATABASE_ADAPTER=postgresql
      - DATABASE_NAME=block_production
      - DATABASE_HOST=192.168.0.121
      - DATABASE_PORT=5432
      - DATABASE_USER=Alone
      - DATABASE_PASS=Alone123!*
      - RABBITMQ_HOST=192.168.0.121
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - ENCRYPTION_KEY=8eH4y0P/vGq3Gf0GTmqooDPrYL4tbNFDqFyRhQGWA9s=
      - BLOCK_EXCHANGE_NAME=blockchain
      - BLOCK_QUEUE_NAME='blockchain_queue'
      - BLOCK_ROUTEING_KEY=blockchain.fetch_block
      - RPC_BSC_NETWORK=https://data-seed-prebsc-1-s1.bnbchain.org:8545
      - RPC_TRON_NETWORK=https://api.nileex.io
      - SECRET_KEY_BASE=12345678913456
    command: bash -c "bundle exec ruby bin/block.rb run"
    logging:
      driver: "json-file"
      options:
          max-size: "50m"

  deposit:
    image: "oeypayblockchain:0.2"
    restart: always
    environment:
      - GROUP_ID=1
      - DATABASE_ADAPTER=postgresql
      - DATABASE_NAME=postgres
      - DATABASE_HOST=192.168.1.47
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASS=postgres
    command: bash -c "bundle exec ruby lib/daemons/daemons.rb deposit"
    logging:
      driver: "json-file"
      options:
          max-size: "50m"
  blockchain_1:
    image: "oeypayblockchain:0.2"
    restart: always
    environment:
      - GROUP_ID=1
      - DATABASE_ADAPTER=postgresql
      - DATABASE_NAME=postgres
      - DATABASE_HOST=192.168.1.47
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASS=postgres
    command: bash -c "bundle exec ruby lib/daemons/daemons.rb blockchain"
    logging:
      driver: "json-file"
      options:
          max-size: "50m"
  blockchain_2:
    image: "oeypayblockchain:0.2"
    restart: always
    environment:
      - GROUP_ID=2
      - DATABASE_ADAPTER=postgresql
      - DATABASE_NAME=postgres
      - DATABASE_HOST=192.168.1.47
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASS=postgres
    command: bash -c "bundle exec ruby lib/daemons/daemons.rb blockchain"
    logging:
      driver: "json-file"
      options:
          max-size: "50m"