version: '3.6'

services:
  blockchain_1:
    image: "oeypayblockchain:0.2"
    restart: always
    environment:
      - GROUP_ID=1
      - DATABASE_ADAPTER=postgresql
      - DATABASE_NAME=postgres
      - DATABASE_HOST=192.168.1.47
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASS=postgres
    command: bash -c "bundle exec ruby lib/daemons/daemons.rb blockchain"
    logging:
      driver: "json-file"
      options:
          max-size: "50m"
  blockchain_2:
    image: "oeypayblockchain:0.2"
    restart: always
    environment:
      - GROUP_ID=2
      - DATABASE_ADAPTER=postgresql
      - DATABASE_NAME=postgres
      - DATABASE_HOST=192.168.1.47
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASS=postgres
    command: bash -c "bundle exec ruby lib/daemons/daemons.rb blockchain"
    logging:
      driver: "json-file"
      options:
          max-size: "50m"