version: '3.6'

services:
  backend:
    image: "gadai:0.1"
    restart: always
    environment:
      - GROUP_ID=
      - RAILS_ROOT=
      - DATABASE_ADAPTER=
      - DATABASE_NAME=
      - DATABASE_HOST=
      - DATABASE_PORT=
      - DATABASE_USER=
      - DATABASE_PASS=
      - RABBITMQ_HOST=
      - RABBITMQ_PORT=
      - RABBITMQ_USERNAME=
      - RABBITMQ_PASSWORD=
      - ENCRYPTION_KEY=
      - BLOCK_EXCHANGE_NAME=
      - BLOCK_QUEUE_NAME=
      - BLOCK_ROUTEING_KEY=
      - RPC_BSC_NETWORK=
      - RPC_TRON_NETWORK=
      - SECRET_KEY_BASE=
    ports:
      - "3000:3000"
    command: bash -c "bundle exec puma --config config/puma.rb"
    logging:
      driver: "json-file"
      options:
          max-size: "50m"

  deposit_address:
    image: "gadai:0.1"
    restart: always
    environment:
      - GROUP_ID=
      - RAILS_ROOT=
      - DATABASE_ADAPTER=
      - DATABASE_NAME=
      - DATABASE_HOST=
      - DATABASE_PORT=
      - DATABASE_USER=
      - DATABASE_PASS=
      - RABBITMQ_HOST=
      - RABBITMQ_PORT=
      - RABBITMQ_USERNAME=
      - RABBITMQ_PASSWORD=
      - ENCRYPTION_KEY
      - BLOCK_EXCHANGE_NAME=
      - BLOCK_QUEUE_NAME=
      - BLOCK_ROUTEING_KEY=
      - SECRET_KEY_BASE
    command: bash -c "bundle exec ruby lib/daemons/amqp_daemon.rb deposit_coin_address"
    logging:
      driver: "json-file"
      options:
          max-size: "50m"
    
  proces_block:
    image: "gadai:0.1"
    restart: always
    volumes:
      - ./app/services:/home/app/app/services
    ports:
      - "3001:3000"
    environment:
      - GROUP_ID=
      - RAILS_ROOT=
      - DATABASE_ADAPTER=
      - DATABASE_NAME=
      - DATABASE_HOST=
      - DATABASE_PORT=
      - DATABASE_USER=
      - DATABASE_PASS=
      - RABBITMQ_HOST=
      - RABBITMQ_PORT=
      - RABBITMQ_USERNAME=
      - RABBITMQ_PASSWORD=
      - ENCRYPTION_KEY=
      - BLOCK_EXCHANGE_NAME=
      - BLOCK_QUEUE_NAME=
      - BLOCK_ROUTEING_KEY=
      - SECRET_KEY_BASE=
    command: bash -c "bundle exec ruby bin/block.rb run"
    logging:
      driver: "json-file"
      options:
          max-size: "50m"

  proces_block:
    image: "gadai:0.1"
    restart: always
    volumes:
      - ./app/services:/home/app/app/services
    ports:
      - "3001:3000"
    environment:
      - GROUP_ID=
      - RAILS_ROOT=
      - DATABASE_ADAPTER=
      - DATABASE_NAME=
      - DATABASE_HOST=
      - DATABASE_PORT=
      - DATABASE_USER=
      - DATABASE_PASS=
      - RABBITMQ_HOST=
      - RABBITMQ_PORT=
      - RABBITMQ_USERNAME=
      - RABBITMQ_PASSWORD=
      - ENCRYPTION_KEY=
      - BLOCK_EXCHANGE_NAME=
      - BLOCK_QUEUE_NAME=
      - BLOCK_ROUTEING_KEY=
      - SECRET_KEY_BASE=
    command: bash -c "bundle exec ruby bin/block.rb run"
    logging:
      driver: "json-file"
      options:
          max-size: "50m"

  deposit:
    image: "gadai:0.1"
    restart: always
    environment:
      - GROUP_ID=
      - RAILS_ROOT=
      - DATABASE_ADAPTER=
      - DATABASE_NAME=
      - DATABASE_HOST=
      - DATABASE_PORT=
      - DATABASE_USER=
      - DATABASE_PASS=
      - RABBITMQ_HOST=
      - RABBITMQ_PORT=
      - RABBITMQ_USERNAME=
      - RABBITMQ_PASSWORD=
      - ENCRYPTION_KEY=
      - BLOCK_EXCHANGE_NAME=
      - BLOCK_QUEUE_NAME=
      - BLOCK_ROUTEING_KEY=
      - SECRET_KEY_BASE=
    command: bash -c "bundle exec ruby lib/daemons/daemons.rb deposit"
    logging:
      driver: "json-file"
      options:
          max-size: "50m"
  blockchain_1:
    image: "gadai:0.1"
    restart: always
    environment:
      - GROUP_ID=
      - RAILS_ROOT=
      - DATABASE_ADAPTER=
      - DATABASE_NAME=
      - DATABASE_HOST=
      - DATABASE_PORT=
      - DATABASE_USER=
      - DATABASE_PASS=
      - RABBITMQ_HOST=
      - RABBITMQ_PORT=
      - RABBITMQ_USERNAME=
      - RABBITMQ_PASSWORD=
      - ENCRYPTION_KEY=
      - BLOCK_EXCHANGE_NAME=
      - BLOCK_QUEUE_NAME=
      - BLOCK_ROUTEING_KEY=
      - SECRET_KEY_BASE=
    command: bash -c "bundle exec ruby lib/daemons/daemons.rb blockchain"
    logging:
      driver: "json-file"
      options:
          max-size: "50m"
  blockchain_2:
    image: "gadai:0.1"
    restart: always
    environment:
      - GROUP_ID=
      - RAILS_ROOT=
      - DATABASE_ADAPTER=
      - DATABASE_NAME=
      - DATABASE_HOST=
      - DATABASE_PORT=
      - DATABASE_USER=
      - DATABASE_PASS=
      - RABBITMQ_HOST=
      - RABBITMQ_PORT=
      - RABBITMQ_USERNAME=
      - RABBITMQ_PASSWORD=
      - ENCRYPTION_KEY=
      - BLOCK_EXCHANGE_NAME=
      - BLOCK_QUEUE_NAME=
      - BLOCK_ROUTEING_KEY=
      - SECRET_KEY_BASE=
    command: bash -c "bundle exec ruby lib/daemons/daemons.rb blockchain"
    logging:
      driver: "json-file"
      options:
          max-size: "50m"