version: '3.6'

services:
  backend:
    image: "gadai-prod:0.1"
    restart: always
    environment:
      - GROUP_ID=2
      - RAILS_ROOT=/home/app
      - DATABASE_ADAPTER=postgresql
      - DATABASE_NAME=blockhain_production
      - DATABASE_HOST=192.168.0.121
      - DATABASE_PORT=5432
      - DATABASE_USER=Alone
      - DATABASE_PASS=Alone123!*
      - RABBITMQ_HOST=192.168.0.121
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - ENCRYPTION_KEY=8eH4y0P/vGq3Gf0GTmqooDPrYL4tbNFDqFyRhQGWA9s=
      - BLOCK_EXCHANGE_NAME=blockchain
      - BLOCK_QUEUE_NAME=blockchain_queue
      - BLOCK_ROUTEING_KEY=blockchain.fetch_block
      - SECRET_KEY_BASE=12345678913456
      - DEPOSIT_PROCESS_ROUTING=deposit.process
      - DEPOSIT_EXCHANGE_NAME=deposit
    ports:
      - "3000:3000"
    command: bash -c "bundle exec puma --config config/puma.rb"
    logging:
      driver: "json-file"
      options:
          max-size: "50m"

  deposit_address:
    image: "gadai:0.1"
    restart: always
    environment:
      - GROUP_ID=0
      - RAILS_ROOT=/home/app
      - DATABASE_ADAPTER=
      - DATABASE_NAME=
      - DATABASE_HOST=
      - DATABASE_PORT=
      - DATABASE_USER=
      - DATABASE_PASS=
      - RABBITMQ_HOST=
      - RABBITMQ_PORT=
      - RABBITMQ_USERNAME=
      - RABBITMQ_PASSWORD=
      - ENCRYPTION_KEY=
      - BLOCK_EXCHANGE_NAME=blockchain
      - BLOCK_QUEUE_NAME=blockchain_queue
      - BLOCK_ROUTEING_KEY=blockchain.fetch_block
      - SECRET_KEY_BASE=
      - DEPOSIT_PROCESS_ROUTING=deposit.process
      - DEPOSIT_EXCHANGE_NAME=deposit
    command: bash -c "bundle exec ruby lib/daemons/amqp_daemon.rb deposit_coin_address"
    logging:
      driver: "json-file"
      options:
          max-size: "50m"

  cron_job:
    image: "gadai:0.1"
    restart: always
    environment:
      - GROUP_ID=0
      - RAILS_ROOT=/home/app
      - DATABASE_ADAPTER=
      - DATABASE_NAME=
      - DATABASE_HOST=
      - DATABASE_PORT=
      - DATABASE_USER=
      - DATABASE_PASS=
      - RABBITMQ_HOST=
      - RABBITMQ_PORT=
      - RABBITMQ_USERNAME=
      - RABBITMQ_PASSWORD=
      - ENCRYPTION_KEY=
      - BLOCK_EXCHANGE_NAME=blockchain
      - BLOCK_QUEUE_NAME=blockchain_queue
      - BLOCK_ROUTEING_KEY=blockchain.fetch_block
      - SECRET_KEY_BASE=
      - DEPOSIT_PROCESS_ROUTING=deposit.process
      - DEPOSIT_EXCHANGE_NAME=deposit
    command: bash -c "bundle exec ruby lib/daemons/amqp_daemon.rb cron_job"
    logging:
      driver: "json-file"
      options:
          max-size: "50m"

  withdraw_coin:
    image: "gadai:0.1"
    restart: always
    environment:
      - GROUP_ID=0
      - RAILS_ROOT=/home/app
      - DATABASE_ADAPTER=
      - DATABASE_NAME=
      - DATABASE_HOST=
      - DATABASE_PORT=
      - DATABASE_USER=
      - DATABASE_PASS=
      - RABBITMQ_HOST=
      - RABBITMQ_PORT=
      - RABBITMQ_USERNAME=
      - RABBITMQ_PASSWORD=
      - ENCRYPTION_KEY=
      - BLOCK_EXCHANGE_NAME=blockchain
      - BLOCK_QUEUE_NAME=blockchain_queue
      - BLOCK_ROUTEING_KEY=blockchain.fetch_block
      - SECRET_KEY_BASE=
      - DEPOSIT_PROCESS_ROUTING=deposit.process
      - DEPOSIT_EXCHANGE_NAME=deposit
    command: bash -c "bundle exec ruby lib/daemons/amqp_daemon.rb withdraw_coin"
    logging:
      driver: "json-file"
      options:
          max-size: "50m"

  proces_block:
    image: "gadai:0.1"
    restart: always
    volumes:
      - ./app/services:/home/app/app/services
    environment:
      - GROUP_ID=0
      - RAILS_ROOT=/home/app
      - DATABASE_ADAPTER=
      - DATABASE_NAME=
      - DATABASE_HOST=
      - DATABASE_PORT=
      - DATABASE_USER=
      - DATABASE_PASS=
      - RABBITMQ_HOST=
      - RABBITMQ_PORT=
      - RABBITMQ_USERNAME=
      - RABBITMQ_PASSWORD=
      - ENCRYPTION_KEY=
      - BLOCK_EXCHANGE_NAME=blockchain
      - BLOCK_QUEUE_NAME=blockchain_queue
      - BLOCK_ROUTEING_KEY=blockchain.fetch_block
      - SECRET_KEY_BASE=
      - DEPOSIT_PROCESS_ROUTING=deposit.process
      - DEPOSIT_EXCHANGE_NAME=deposit
    command: bash -c "bundle exec ruby bin/block.rb run"
    logging:
      driver: "json-file"
      options:
          max-size: "50m"

  deposit:
    image: "gadai:0.1"
    restart: always
    environment:
      - GROUP_ID=0
      - RAILS_ROOT=/home/app
      - DATABASE_ADAPTER=
      - DATABASE_NAME=
      - DATABASE_HOST=
      - DATABASE_PORT=
      - DATABASE_USER=
      - DATABASE_PASS=
      - RABBITMQ_HOST=
      - RABBITMQ_PORT=
      - RABBITMQ_USERNAME=
      - RABBITMQ_PASSWORD=
      - ENCRYPTION_KEY=
      - BLOCK_EXCHANGE_NAME=blockchain
      - BLOCK_QUEUE_NAME=blockchain_queue
      - BLOCK_ROUTEING_KEY=blockchain.fetch_block
      - SECRET_KEY_BASE=
      - DEPOSIT_PROCESS_ROUTING=deposit.process
      - DEPOSIT_EXCHANGE_NAME=deposit
    command: bash -c "bundle exec ruby lib/daemons/daemons.rb deposit"
    logging:
      driver: "json-file"
      options:
          max-size: "50m"
  blockchain_1:
    image: "gadai:0.1"
    restart: always
    environment:
      - GROUP_ID=1
      - RAILS_ROOT=/home/app
      - DATABASE_ADAPTER=
      - DATABASE_NAME=
      - DATABASE_HOST=
      - DATABASE_PORT=
      - DATABASE_USER=
      - DATABASE_PASS=
      - RABBITMQ_HOST=
      - RABBITMQ_PORT=
      - RABBITMQ_USERNAME=
      - RABBITMQ_PASSWORD=
      - ENCRYPTION_KEY=
      - BLOCK_EXCHANGE_NAME=blockchain
      - BLOCK_QUEUE_NAME=blockchain_queue
      - BLOCK_ROUTEING_KEY=blockchain.fetch_block
      - SECRET_KEY_BASE=
      - DEPOSIT_PROCESS_ROUTING=deposit.process
      - DEPOSIT_EXCHANGE_NAME=deposit
    command: bash -c "bundle exec ruby lib/daemons/daemons.rb blockchain"
    logging:
      driver: "json-file"
      options:
          max-size: "50m"
  blockchain_2:
    image: "gadai:0.1"
    restart: always
    environment:
      - GROUP_ID=2
      - RAILS_ROOT=/home/app
      - DATABASE_ADAPTER=
      - DATABASE_NAME=
      - DATABASE_HOST=
      - DATABASE_PORT=
      - DATABASE_USER=
      - DATABASE_PASS=
      - RABBITMQ_HOST=
      - RABBITMQ_PORT=
      - RABBITMQ_USERNAME=
      - RABBITMQ_PASSWORD=
      - ENCRYPTION_KEY=
      - BLOCK_EXCHANGE_NAME=blockchain
      - BLOCK_QUEUE_NAME=blockchain_queue
      - BLOCK_ROUTEING_KEY=blockchain.fetch_block
      - SECRET_KEY_BASE=
      - DEPOSIT_PROCESS_ROUTING=deposit.process
      - DEPOSIT_EXCHANGE_NAME=deposit
    command: bash -c "bundle exec ruby lib/daemons/daemons.rb blockchain"
    logging:
      driver: "json-file"
      options:
          max-size: "50m"