connect:
  host: <%= ENV.fetch('RABBITMQ_HOST', 'localhost') %>
  port: <%= ENV.fetch('RABBITMQ_PORT', '5672') %>
  username: <%= ENV.fetch('RABBITMQ_USER', 'guest') %>
  password: <%= ENV.fetch('RABBITMQ_PASSWORD', 'guest') %>

exchange:
  events:
    name: peatio.events
    type: direct
  payer:
    name: peatio.payer
    type: direct
  schaning:
    name: peatio.schaning
    type: direct

queue:
  withdraw_coin:
    name: peatio.withdraw.coin
  deposit_collection_fees:
    name: peatio.deposit.collection_fees
  deposit_collection:
    name: peatio.deposit.collection
  deposit_coin_address:
    name: peatio.deposit.coin.address
    durable: true
  events_processor:
    name: peatio.events.processor
  payer_fee:
    name: peatio.payer.fee
  schaning_block:
    name: peatio.schaning_block_or_hash

binding:
  withdraw_coin:
    queue: withdraw_coin
  deposit_coin_address:
    queue: deposit_coin_address
  events_processor:
    queue: events_processor
    exchange: events
  payer_fee:
    queue: payer_fee
    exchange: payer
  schaning_block:
    queue: schaning_block
    exchange: schaning


channel:
  payer_fee:
    prefetch: 5
  schaning_block:
    prefetch: 5
