default: &default
  host: <%= ENV.fetch("INFLUXDB_HOST", "192.168.1.100").split(',') %>
  port: <%= ENV.fetch("INFLUXDB_PORT", 8086) %>
  username: <%= ENV.fetch("INFLUXDB_USER", "root") %>
  password: <%= ENV.fetch("INFLUXDB_PASS", "root") %>

development:
  <<: *default
  database: nusaexchange_exchange_production

test:
  <<: *default
  database: peatio_test

production:
  <<: *default
  database: <%= ENV.fetch('INFLUXDB_DATABASE_NAME', "exchange_production") %>
