exchanges:
  - name: blockchain
    type: direct
    durable: false
    auto_delete: false
  - name: deposit_address
    type: direct
    durable: false
    auto_delete: false
  - name: withdraw_coin
    type: direct
    durable: false
    auto_delete: false
  - name: deposit
    type: direct
    durable: false
    auto_delete: false
queues:
  - name: blockchain_queue
    durable: true
    auto_delete: false
    bindings:
      - exchange: blockchain
        routing_key: blockchain.fetch_block
  - name: deposit_address_queue
    durable: true
    auto_delete: false
    bindings:
      - exchange: deposit_address
        routing_key: deposit.global_address
  - name: withdraw_coin_queue
    durable: true
    auto_delete: false
    bindings:
      - exchange: withdraw_coin
        routing_key: withdraw.coin_or_token
  - name: deposit_proces_queue
    durable: true
    auto_delete: false
    bindings:
      - exchange: deposit
        routing_key: deposit.process