defaults: &defaults
  # Configure Redis URL, for a TCP connection:
  # `redis://:[password]@[hostname]:[port]/[db]`
  # (password, port and database are optional).
  REDIS_URL     :'redis://192.168.1.100:6379'
  REDIS_PASSWORD: ~
  REDIS_CLUSTER :  false

  # Configuration variables for logger.
  LOG_LEVEL: ~ # Default level for production is warn, otherwise – debug.

  # Configuration variables for API CORS.
  #
  # Set list of allowed origins using the variable below.
  # By default it allows access to API from all origins.
  # See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin
  API_CORS_ORIGINS:           '*'
  # Access-Control-Allow-Credentials response header is not supported
  # if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’.
  API_CORS_ALLOW_CREDENTIALS: 'false'
  # The Access-Control-Max-Age response header indicates how long 
  # the results of a preflight request can be cached.
  # Default value 3600. 
  API_CORS_MAX_AGE:           ~

  # Configuration variables for Sentry.
  SENTRY_DSN_BACKEND:  ~          # Specify Sentry DSN used for Rails application.

  JWT_PUBLIC_KEY: 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2aDGJzecDBrGXBL/animkEChRt844XoxznXSlff2ppbpqm4xy+U1rrDEK8sEEBoc2qv0qbU88rS6iTg6MTd4u4a/oZCogNleUn4uXx+IPluT67nP1s9d1X/s+ADU4Bk4L9tQAIx7GgVD52AchVoj1D8SJCEm5vmCvmNeneJ+Ok3RAgLeA0gOfZB7UMVHyfI/rmN3VorFQjRPZ9ActjDDRgPaMYa0JS17h+EOuFczGl6V663XAGiVU0kaiA3+5xHdKygx8v0xsPWjiQ89q5LX1CNbU7jx1SFPpQLBlKIIAHaz0vYrVm1Yc1wGX+QDOx4QSOAc2sfv3AboVk95EDFL6wIDAQAB'
  JWT_ALGORITHM: RS256  # JWT signing algorithm (mandatory).
  JWT_ISSUER: ~      # JWT issuer name (optional).
  JWT_AUDIENCE: peatio # Could be comma-separated value (optional).
  JWT_DEFAULT_LEEWAY: ~      # Seconds (optional).
  JWT_ISSUED_AT_LEEWAY: '180'    # Seconds (optional).
  JWT_EXPIRATION_LEEWAY: ~      # Seconds (optional).
  JWT_NOT_BEFORE_LEEWAY: ~      # Seconds (optional).
  PEATIO_JWT_PRIVATE_KEY: ~

  # Scout APM configuration variables.
  SCOUT_KEY:       ~          # Your organization key for Scout APM. Found on the settings screen.
  SCOUT_APP_NAME:  ~          # Application name in APM Web UI.
  SCOUT_LOG_LEVEL: warn       # Verboseness of logs (debug, info, warn, error)
  SCOUT_ENV:       production # List of Rails environments for which Scout should be enabled.

  MINIMUM_MEMBER_LEVEL_FOR_DEPOSIT:  '3'
  MINIMUM_MEMBER_LEVEL_FOR_WITHDRAW: '3'
  MINIMUM_MEMBER_LEVEL_FOR_TRADING:  '3'

  # Event API configuration.

  # JWT configuration.
  # You can generate keypair using:
  #
  #   ruby -e "require 'openssl'; require 'base64'; OpenSSL::PKey::RSA.generate(2048).tap { |p| puts '', 'PRIVATE RSA KEY (URL-safe Base64 encoded, PEM):', '', Base64.urlsafe_encode64(p.to_pem), '', 'PUBLIC RSA KEY (URL-safe Base64 encoded, PEM):', '', Base64.urlsafe_encode64(p.public_key.to_pem) }"
  #
  EVENT_API_JWT_PRIVATE_KEY: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBdFVGcU9QYlVWaHVHRG12M1pudGNsY2preDMzSTVXMFlzRnBCN1NHL1RiUTBOeWYxCkZvcFZoV1l4WE05SDhjVG11M3JXZlg3K2J4OVV4TmlTL2QzT2h0akNtRUJEcjZ0MzJxVitoWE9VbjdERE5ZOVMKcU5UMEhzc0F0bFhoYnFnSXptT1gwK2I5YWQzUDBLbE4zbjdQdXdzb05UekllVDV2ZkF6Z0NXZmxVek5IK29lagpsZnpJK2N1LzJCbUJaV2F0LzBiemw1L2RnMElveSthSHJnV0pybzFpcWFXZnpHdXpRSCtoTjEwN01SbFRyTEdOCnlTeFkzY3FyTnJQcUZ1UkJYd2dzdU91Tlg3a211djdDZXZqMFJpdDV5czdoV1lwQzhnblhHaUc4TjIvWnNaa3MKY0I5RVExeFZpZlhqS1hHRkJETDdYajFNdFR6SGQwakZwUk5uNFFJREFRQUJBb0lCQUVMekFaZysyNWxlbXpxUwplSlJhOW96QTRuZ3BKdDVQV0xJeTlHenhiU2IzYTkzL25WQ1JFaHV1N29hNGJYdUkzaXpicDRROU54KzJjK290CmtNWENldmxsOFNLcGdoYk4vL3c3NnFyQ1VXQld1eFA2ZDI2ekVlU1oyUTZBVkQ4NlE5NXYvUEdoUFhNd0lnV1IKczVoK1FKNTI5WWdNaG9QNkl0V3dMOFJwb3RRQzJ0RHV5ZzY1YUozaFZYV2lXNmozak9BV2NiTzFyY09MTFcxSwpzY01vQXltY1VQbGh1Qng0bW43dlFrVXVuV0s5MWI0Y1FkVXN3ZDBJWFVIZ2Z1VFQyWDlnTVNpQlZqVUhZVzRFCnJaSUY4dGtiR1FkMnEyUzA0N2srT0JZaVVQSkFZaEN0cjBKbDBzaHVxRUkveVZwdlZzRGtoSXFtRi9GUlNTcXMKaEdsbkY5RUNnWUVBMzh0Q3lwUmR2RE5sZTJjazQwTVgzS2xmbVN6RkJtRmxmYVUrQ1p0bDJqeEFmdjMrNkh6YwpXTWdCTmdCa2E4UGRqT05iTDF1MlVTMy9vNlhleU9laHFsQ1J0TEY4ZmZkQkVvTWxTdDFlRm5GSGxQYjZwTHFHClVaODVPeSs5WVoxUUlGdTZsS2lOdE1CeUgxUzZucy90Q0V0QUdNUy9yUUF0b3R4UnZWZHVyWFVDZ1lFQXoxY0IKVFdlb3JqZUJKWVRaa3JydzhPcnQvSGxaaWpRK0pKQVZaZDM3UnFYUm93YWxTekluRkd4N2ttUmlWakpPQTVpTgpoVHdrTjhrOE55ODVSV0dIS0ducGVLVkhIcWR0MlFDQnlsOHBkNkU5Z2tJZnB1RWI1dS9mSFhZT3lYMkExY0wzCjhXSnZSZWROa2tkZzVnNTg2Y1lxUzhLWFBlN1BMWEpqNnBrQ1p6MENnWUJBbXFYYVkwQTMvMEpSZ0hJV3BSeXoKVjdYQU96dFpYeTUwT2dxUnJXbVd1WVFJNVB2OFUyY3N2ZmdUaGNOM2xLQlZkcUN4S0RHV2Q4ZnZqd2VrU2JIUwp2OVdBS3loOEdLK1JUNGlwZHdRZFNIQllvWCt6cENENFdSV2xiMStsV1V0ek8rZTkySGFuOGxJL2x5OFVmNE8yCnZEcHhyQUtGUjZMaysrTWczS2VYclFLQmdFWVhpSll0UThYWmQ2eENVL2NaZ1ZoQVkwR2xtRkp6Uk1yQmRxcGcKTjVEemY0SVlQZ3JFb3BkeDhQaFZQVFVjZm1rU3lrelBQd01vNFZWYWZvYm82SE1PRXVJNUpXakVld3NQODlDQgpDUmlyQm9zaFpXZlowNy9uT1VyUlhVQmFVQkp6ZmJRNWJacDVEaTAwT2hxcnJTaXVXQ0FTWVdTTGRiaE1ZbUN0Clp6V1ZBb0dBYXNmcWtQL2V2WWtKWkNFL3NaUEhkNDNTMkNHeE5CVVZnR2dOalhIWnZiYVdPZXJ4MVZEQnd3bmEKdWNPb3hLeEt3NVZCNGdvbWlXOHRnQzUvTGpnNHpWTEZqOGozd2lWZjFKNXBmS1lDajVRUktpZjVaVUV4SEw0TwpURUFXVzcvNzZpZFkyNGZaMnM5QW50anhDWVhWU3U2R2NsdkhpbXFwOGJpakVMeUIyMkE9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg # Private key. Must be URL-safe Base64 encoded in PEM format.
  EVENT_API_JWT_ALGORITHM:   RS256

  # RabbitMQ configuration.
  # You can use just «EVENT_API_RABBITMQ_URL» or specify configuration per separate variable.
  EVENT_API_RABBITMQ_URL:      ~
  EVENT_API_RABBITMQ_HOST:     192.168.1.100
  EVENT_API_RABBITMQ_PORT:     "5672"
  EVENT_API_RABBITMQ_USERNAME: guest
  EVENT_API_RABBITMQ_PASSWORD: guest

  BULLET: 'false'

  # Configure Vault to verify OTP for Withdraw API
  VAULT_ADDR:   http://192.168.1.100:8200
  VAULT_TOKEN:  "s.4k6JV7BJBbIUOlGeP2JZLQZG"

  # Configure to limit currencies and markets on the platform.
  MAX_CURRENCIES: ~
  MAX_MARKETS:    ~

development:
  <<: *defaults

  # Development configuration variables for Event API JWT.
  EVENT_API_JWT_PRIVATE_KEY:  LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBb3VLVHh2SFVJVDJENmdXaWJRcS9kbW9BUUwyeWJ6SGFiUXRlc1AyL2o1VjkvUExaCmhHNWtLVkpPWjcxVVdMQ3BjZTQxeHZzQ0lKd0Q5MnVDNW5Lak5wblRDTWpwTUJNMGg0aFF4a2VOeHdNeU41N1gKM1QzbWFCVmZzUTNCblErSm84L0tzdUxhODlvY0dDeDgvYlUyOGNld2FxRk8ydUVMWWJiaUZadGFCenFJd0ZCdQpTM3hGQmt6NE16MGgvWEIxTjl5ZDg5d25OMm1oWVBsU0xrTGVUdFoyeWswK2krZHhZd2V4MEozOXJDS0hnRWRKCko1NTZHNmdtZWpJZ3dtcHNVeHJpdkVJRU5jR09POHdmQVBUVy92SFZmc2ROTExHejRtZE9CWmxsa2orcFFQODYKTnFSUjRKSnFDdEg3dHYyaXVBSGI4NnB5anVlZkVGU3ljMmxZRXdJREFRQUJBb0lCQUJrUlViamVZczB5MEdobApzWmVpZmREVmczQnpRVkRIbFZ3TzBlWGZSMm5ya2RZcDhidmwyVmhhcUdKaXl1WlRXZUNFenBYdTcyYmhXK0xxCkV0MHdhMW50MW9LVm1QMmpGd1I4d0NHanhYZ0pUK01yZVFFOWs0WVZOQUxsb1JSdzNiZnVOTDNQRis5TGMrTnMKaFZmdVdhUmdIUkJyL3R6RW9hSEtLWVUxd1djM0poSitNRklNVkZBT0RvaGp6bXNlV2lzTDNnbzVrUC9KYUpVZwprNm13Wnd0QzRvQ3pPQ3FoRGF0WVI3cktJbXMyS1lCNVBwaTRDTThkRzJGTzBwWGxXUU9XT0t2N01TUjlVeEtzCmd4YWFRRlhjajBQM2lSRFVQMDRkSWtqblNtemZmR0F2L3lBTHovZjk0V1lIK3gvd01DWms4ejJ4bnRJclllM3UKN0NOd045RUNnWUVBMEplcThCaXlKczF6YlBpcTlWWnR5L3R0M1dhaXJDbUl4cXRwU2syVU9UNmh2TldiMTUxVwpBMGRWYWEvSVBhdDV4ZkNWdGhkNlB3UGpJbWVPVXQ4Mlhib2JYeE8zREJUcmVzTlRNWUhiMGVUK09sSG04SU5uCnVwOGFxZWpWejc1ME5VYUxGWWpxWk1wVVR1Z2FVREIzNWZ1bXg0SXliNm5LRGMvSStrN25qUlVDZ1lFQXgrZVAKcE4vR1dqYjJUOU1CUm1xdkVtSGxKOXBZSEZpWGZlWnJHdzg3Q2E5WjVDYVp1VzBrSVAwSlhWSDZOOThqL2RvbApDTHZPdE5oZVFoaGUrTU91VXJMT0ttaytpckM5SEk2cW9aT3Nkc0lCc0pXSHdPanB1UW00OWNvdXc0K2ZKOWRxCjN2cTE2bG5EQlNoRU5HTEFhdVBzWDhLRUlYVzhRRnBDM3ppbXFvY0NnWUI2bTh2VVdRL09reEQzeXFyaWpxejMKSzVFR2hKKzF4cXdvNnZSMndtY1B4dXJXemxCT1NxTVdSa1hFVzVpOTl4OGE1REY3MlF6NElWYlBFRU91SHBvYwpPWnFCSmx0LzlJUDlvdll4c1h6K1FUWFdIZkk3Q1dKZFpjd01kMW5HUk5LVnhpTld3eVhUbk1JMXAyUmdJajAzCnA5WCtpMThPRjZVMnZSNExVM256aVFLQmdBVVZzOGFxMW4zRzloN3pyQTJoZXhDSm91MlBsVHdyV0xjZ0hFdFUKNk5pSE9FOGdXRHFxTndnTHg2Z3pCSjFWTkxJcFVWWFdpUng2Z0hOSDhXcDhkN3VzeHFlM2c1cTlnaUh1MHhKSApFbFQyL0ZvRWc2NTVmakJ4dWQydXBkL2RrRnZRRSt6V0RiaUhUZm1jbTVlRmg0VndoTHV1MC9PUjdoYm85TmgrCnRXYVRBb0dCQUwxVjFUTWZZRFhwYjFwaFBaV2pQL29iV1NqK2VyUXlYdit3TTIxVzRYWFI4YTBkV2hOVXdVeDAKdU9WZ2s1ZlN1OExtNG0zWGNYZ09wV0VJVkZJTzFodDFNN0xxZ0VGNGhFOHl6Y0Vldy9HWXR4VkpCTWEyODVpVQpaVUtkeCt6QWd5VFlnYk50VkVseTVobGRuT2orVmNzanVEL3krWEhXWVl5OVpLa2pNdDhECi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
  # Event API JWT public key value is.
  # EVENT_API_JWT_PUBLIC_KEY: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFvdUtUeHZIVUlUMkQ2Z1dpYlFxLwpkbW9BUUwyeWJ6SGFiUXRlc1AyL2o1VjkvUExaaEc1a0tWSk9aNzFVV0xDcGNlNDF4dnNDSUp3RDkydUM1bktqCk5wblRDTWpwTUJNMGg0aFF4a2VOeHdNeU41N1gzVDNtYUJWZnNRM0JuUStKbzgvS3N1TGE4OW9jR0N4OC9iVTIKOGNld2FxRk8ydUVMWWJiaUZadGFCenFJd0ZCdVMzeEZCa3o0TXowaC9YQjFOOXlkODl3bk4ybWhZUGxTTGtMZQpUdFoyeWswK2krZHhZd2V4MEozOXJDS0hnRWRKSjU1Nkc2Z21laklnd21wc1V4cml2RUlFTmNHT084d2ZBUFRXCi92SFZmc2ROTExHejRtZE9CWmxsa2orcFFQODZOcVJSNEpKcUN0SDd0djJpdUFIYjg2cHlqdWVmRUZTeWMybFkKRXdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==

test:
  <<: *defaults

production:
  <<: *defaults
